FROM oven/bun:1.3.3 AS base

# --- Prepare stage ---
FROM base AS prepare
WORKDIR /app

# Install turbo globally
RUN bun add -g turbo@^2.6.1

# Copy everything
COPY . .

# Generate a partial monorepo with a pruned lockfile for a target workspace.
RUN turbo prune worker --docker

# --- Builder stage ---
FROM base AS builder
WORKDIR /app

# Prune and copy dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the files (as they change more often)
COPY --from=prepare /app/out/full/ .

# Build the app
RUN bunx turbo run build

# --- Runner stage ---
FROM base AS runner
WORKDIR /app

# Set environment variables
ENV NODE_ENV=production \
    HOSTNAME="0.0.0.0"

# Copy only the necessary files from the builder stage
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/package.json ./package.json
# COPY --from=builder /app/packages ./packages
# COPY --from=builder /app/apps/worker/node_modules ./apps/worker/node_modules
# COPY --from=builder /app/apps/worker/dist ./apps/worker/dist
# COPY --from=builder /app/apps/worker/package.json ./apps/worker/package.json

COPY --from=builder /app/apps/worker/logr-worker ./logr-worker

USER bun

ENTRYPOINT [ "./logr-worker" ]